FROM centos:8

RUN yum -y --enablerepo=extras install epel-release yum-utils
RUN dnf config-manager --enable PowerTools
RUN yum -y install gcc-c++ git yasm bzip2 make openssl-devel libtool-ltdl-devel \
    xmlsec1-devel ImageMagick-devel ImageMagick-c++-devel libtool xmlsec1-openssl-devel pcre-devel xz-devel pulseaudio-libs-devel \
    alsa-lib-devel gtk2-devel libcurl-devel libicu-devel libsamplerate-devel libzip-devel pangomm-devel nettle-devel \
    gettext libssh-devel libsndfile-devel rpm-build boost-devel compat-wxGTK3-gtk2-devel nasm python2

RUN mkdir /src

# libx264 is not packaged by Centos as far as I can see
ADD http://ftp.videolan.org/pub/videolan/x264/snapshots/x264-snapshot-20170705-2245.tar.bz2 /src/
RUN cd /src && tar xjf x264-snapshot-20170705-2245.tar.bz2 && cd x264-snapshot-20170705-2245 && \
    ./configure --enable-static --disable-shared && make -j4 && make install

# Neither is libxml++
ADD http://ftp.gnome.org/pub/GNOME/sources/libxml++/3.0/libxml++-3.0.1.tar.xz /src/
RUN cd /src && tar xJf libxml++-3.0.1.tar.xz && cd libxml++-3.0.1 && ./configure --enable-static --disable-shared && make -j4 && make install

include add_users
