#!/usr/bin/python

import os
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--no-cache', help='pass --no-cache to docker', action='store_true')
parser.add_argument('distro', help="build just this distribution", nargs='?')
args = parser.parse_args()

targets = []
if args.distro is not None:
    targets.append(args.distro)
else:
    for target in os.listdir('.'):
        if os.path.isdir(target) and target != '.git':
            targets.append(target)

for target in targets:
    with open(os.path.join(target, 'Dockerfile.in'), 'r') as in_file, open(os.path.join(target, 'Dockerfile'), 'w') as out_file:
        for in_line in in_file.readlines():
            if in_line.startswith('include'):
                with open(in_line.split()[1], 'r') as include_file:
                    for include_line in include_file.readlines():
                        print>>out_file,include_line.strip()
            else:
                print>>out_file,in_line.strip()
    docker = 'docker build '
    if args.no_cache:
        docker += '--no-cache '
    os.system('cd %s; %s -t %s .; cd ..' % (target, docker, target))
