#!/usr/bin/python

import os
import sys
import argparse
from library import make_dockerfile

parser = argparse.ArgumentParser()
parser.add_argument('--no-cache', help='pass --no-cache to docker', action='store_true')
parser.add_argument('distro', help="build just this distribution", nargs='?')
args = parser.parse_args()

targets = []
if args.distro is not None:
    targets.append(args.distro)
else:
    for target in os.listdir('.'):
        if os.path.isdir(target) and target != '.git':
            targets.append(target)

for target in targets:
    if not os.path.isdir(target):
        print>>sys.stderr,'Unknown target %s' % target
        continue
    make_dockerfile(target)
    docker = 'docker build '
    if args.no_cache:
        docker += '--no-cache '
    os.system('cd %s; %s -t %s .; cd ..' % (target, docker, target))
