#!/usr/bin/python

import os
import sys
import argparse
from library import make_dockerfile

for target in os.listdir('.'):
    if os.path.isdir(target) and target != '.git':
        make_dockerfile(target)
