#!/usr/bin/python

import os
import sys
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('distro', help="save just this distribution", nargs='?')
args = parser.parse_args()

targets = []
if args.distro is not None:
    targets.append(args.distro)
else:
    for target in os.listdir('.'):
        if os.path.isdir(target) and target != '.git':
            targets.append(target)

all = ''
for target in targets:
    all += '%s ' % target	

os.system('docker save %s > save.tar' % all)
