FROM base/archlinux

RUN pacman -Syu
RUN pacman --noconfirm -S git gcc pkg-config libxml++2.6 boost openssl xmlsec cmake libx264 libsndfile imagemagick libpulse wxgtk libsamplerate \
    wget pangomm libzip nettle nasm make python icu

include add_users
