FROM ubuntu:18.04

RUN apt update
RUN apt -y upgrade
RUN apt -y install git build-essential autoconf bison flex texinfo unzip help2man gawk libtool libtool-bin libncurses5-dev wget python nano
RUN mkdir /src
RUN cd /src && git clone https://github.com/crosstool-ng/crosstool-ng && cd crosstool-ng && ./bootstrap && ./configure && make && make install
ADD config /src/.config
RUN cd /src && ct-ng build
ADD https://dl.bintray.com/boostorg/release/1.68.0/source/boost_1_68_0.tar.bz2 /src/
RUN cd /src && tar xjf boost_1_68_0.tar.bz2 && cd boost_1_68_0 && ./bootstrap.sh && export PATH=$PATH:/opt/pi/arm-unknown-linux-gnueabihf/bin && echo "using gcc : arm : arm-unknown-linux-gnueabihf-g++ ;" > ~/user-config.jam && ./b2 --with-system --no-tests toolset=gcc-arm link=static cxxflags=-fPIC install --prefix=/opt/pi
ADD wiringPi.patch /src/
RUN cd /src && git clone git://git.drogon.net/wiringPi && cd wiringPi && patch -p1 < /src/wiringPi.patch && cd wiringPi && DESTDIR=/opt/pi PREFIX= CC=/opt/pi/arm-unknown-linux-gnueabihf/bin/arm-unknown-linux-gnueabihf-gcc make install

include add_users
